from dataclasses import dataclass
from typing import Literal, Union


@dataclass(slots=True, frozen=True)
class Person:
    name: str
    gender: Literal['M', 'F']
    age: float
    email: Union[str, None]


users = [
    Person(
        name='Christopher Walter',
        gender='M',
        age=16,
        email='christopher_walter 2008@faulkner-watson.org',
    ),
    Person(
        name='Jacob Thomas',
        gender='M',
        age=18,
        email='jacob_thomas 2006@bond.com',
    ),
    Person(
        name='Marc Sanchez',
        gender='M',
        age=22,
        email='marc_sanchez 2002@kaufman-noble.biz',
    ),
    Person(
        name='Jody Ashley',
        gender='F',
        age=28,
        email='jody_ashley 1996@webster.com',
    ),
    Person(
        name='Mason Tapia',
        gender='M',
        age=22,
        email='mason_tapia 2002@harris.com',
    ),
    Person(
        name='David Baker',
        gender='M',
        age=16,
        email='david_baker 2008@bridges.biz',
    ),
    Person(
        name='Katherine Price DDS',
        gender='F',
        age=26,
        email='katherine_price_dds 1998@ross.biz',
    ),
    Person(
        name='Heather Garcia DDS',
        gender='F',
        age=24,
        email='heather_garcia_dds 2000@smith.com',
    ),
    Person(
        name='Matthew Hughes',
        gender='M',
        age=27,
        email='matthew_hughes 1997@hill.com',
    ),
    Person(
        name='Vanessa Villarreal',
        gender='F',
        age=22,
        email='vanessa_villarreal 2002@alvarez-hurst.com',
    ),
    Person(
        name='James Mendoza',
        gender='M',
        age=31,
        email='james_mendoza 1993@cole.com',
    ),
    Person(
        name='Travis Davis',
        gender='M',
        age=31,
        email='travis_davis 1993@turner.com',
    ),
    Person(
        name='Wanda Fowler',
        gender='F',
        age=23,
        email='wanda_fowler 2001@whitaker.com',
    ),
    Person(
        name='Karen Gonzalez',
        gender='F',
        age=29,
        email='karen_gonzalez 1995@cook.com',
    ),
    Person(
        name='Amanda Miller',
        gender='F',
        age=20,
        email='amanda_miller 2004@obrien.com',
    ),
    Person(
        name='Tammy Henderson',
        gender='F',
        age=28,
        email='tammy_henderson 1996@butler.com',
    ),
    Person(
        name='Dillon Glass',
        gender='M',
        age=24,
        email='dillon_glass 2000@banks-lawson.com',
    ),
    Person(
        name='Ashley Burke',
        gender='F',
        age=28,
        email='ashley_burke 1996@miller.net',
    ),
    Person(
        name='Jeffrey Smith',
        gender='M',
        age=30,
        email='jeffrey_smith 1994@stevens.com',
    ),
    Person(
        name='Mr. James Estrada Jr.',
        gender='M',
        age=22,
        email='mr._james_estrada_jr. 2002@butler.org',
    ),
    Person(
        name='Craig Ramos',
        gender='M',
        age=16,
        email='craig_ramos 2008@serrano-henry.com',
    ),
    Person(
        name='Erika Walker',
        gender='F',
        age=27,
        email='erika_walker 1997@snyder-williams.com',
    ),
    Person(
        name='Theresa Walsh',
        gender='F',
        age=29,
        email='theresa_walsh 1995@stafford.com',
    ),
    Person(
        name='Audrey Ashley',
        gender='F',
        age=19,
        email='audrey_ashley 2005@hall-frank.net',
    ),
    Person(
        name='Katrina Velez',
        gender='F',
        age=17,
        email='katrina_velez 2007@peterson.com',
    ),
    Person(
        name='Christina Armstrong',
        gender='F',
        age=24,
        email='christina_armstrong 2000@james.com',
    ),
    Person(
        name='Shannon Ross',
        gender='F',
        age=31,
        email='shannon_ross 1993@johnson-lucas.com',
    ),
    Person(
        name='Felicia Schneider',
        gender='F',
        age=27,
        email='felicia_schneider 1997@waller-henry.com',
    ),
    Person(
        name='Cassandra Nichols',
        gender='F',
        age=21,
        email='cassandra_nichols 2003@williams-larson.biz',
    ),
    Person(
        name='Rebecca Faulkner',
        gender='F',
        age=16,
        email='rebecca_faulkner 2008@sullivan.biz',
    ),
    Person(
        name='Shannon Baker',
        gender='F',
        age=24,
        email='shannon_baker 2000@cummings.info',
    ),
    Person(
        name='Carmen Smith',
        gender='F',
        age=25,
        email='carmen_smith 1999@rogers.biz',
    ),
    Person(
        name='Sarah Hicks',
        gender='F',
        age=24,
        email='sarah_hicks 2000@rodriguez-rose.com',
    ),
    Person(
        name='Heather Thompson',
        gender='F',
        age=22,
        email='heather_thompson 2002@mills-mclean.info',
    ),
    Person(
        name='William Wang',
        gender='M',
        age=29,
        email='william_wang 1995@russo.org',
    ),
    Person(
        name='Pamela Roberts',
        gender='F',
        age=30,
        email='pamela_roberts 1994@bowen.com',
    ),
    Person(name='Lisa Grant',
           gender='F',
           age=16,
           email='lisa_grant 2008@smith.net'),
    Person(
        name='Raymond Riley',
        gender='M',
        age=27,
        email='raymond_riley 1997@wilson.com',
    ),
    Person(
        name='George Cole',
        gender='M',
        age=23,
        email='george_cole 2001@sosa-rodriguez.com',
    ),
    Person(
        name='David Horton',
        gender='M',
        age=26,
        email='david_horton 1998@baker-benitez.com',
    ),
    Person(
        name='Joshua Scott',
        gender='M',
        age=27,
        email='joshua_scott 1997@reid.com',
    ),
    Person(
        name='Kevin Richardson',
        gender='M',
        age=25,
        email='kevin_richardson 1999@wallace-cunningham.com',
    ),
    Person(
        name='Danielle Lin',
        gender='F',
        age=28,
        email='danielle_lin 1996@cohen.com',
    ),
    Person(
        name='Rebecca Munoz',
        gender='F',
        age=28,
        email='rebecca_munoz 1996@harrison-taylor.com',
    ),
    Person(
        name='Kirk Daniel',
        gender='M',
        age=16,
        email='kirk_daniel 2008@rose.com',
    ),
    Person(
        name='Nicole Bright',
        gender='F',
        age=24,
        email='nicole_bright 2000@taylor.com',
    ),
    Person(
        name='Evelyn Tanner',
        gender='F',
        age=16,
        email='evelyn_tanner 2008@gallagher.com',
    ),
    Person(
        name='Danielle Duran',
        gender='F',
        age=26,
        email='danielle_duran 1998@ellis.com',
    ),
    Person(
        name='Deborah Fernandez',
        gender='F',
        age=24,
        email='deborah_fernandez 2000@perez-garcia.com',
    ),
    Person(
        name='Carol Cruz',
        gender='F',
        age=19,
        email='carol_cruz 2005@lawson.org',
    ),
    Person(
        name='Monica Young',
        gender='F',
        age=22,
        email='monica_young 2002@nelson-nelson.biz',
    ),
    Person(name='Ryan Cox', gender='M', age=21,
           email='ryan_cox 2003@riley.com'),
    Person(
        name='Nancy Serrano',
        gender='F',
        age=24,
        email='nancy_serrano 2000@nelson-anderson.info',
    ),
    Person(
        name='Jose Spencer',
        gender='M',
        age=20,
        email='jose_spencer 2004@arnold-cervantes.info',
    ),
    Person(
        name='Alex Meadows',
        gender='M',
        age=25,
        email='alex_meadows 1999@hansen.com',
    ),
    Person(
        name='Molly Perry',
        gender='F',
        age=26,
        email='molly_perry 1998@moreno.com',
    ),
    Person(
        name='Tiffany Schmidt',
        gender='F',
        age=17,
        email='tiffany_schmidt 2007@gonzalez.com',
    ),
    Person(
        name='Pamela Miller',
        gender='F',
        age=27,
        email='pamela_miller 1997@reese.com',
    ),
    Person(name='Anne Kirk',
           gender='F',
           age=21,
           email='anne_kirk 2003@jones.info'),
    Person(
        name='Oscar Wilson',
        gender='M',
        age=23,
        email='oscar_wilson 2001@reed-wallace.biz',
    ),
    Person(
        name='Garrett Sweeney',
        gender='M',
        age=27,
        email='garrett_sweeney 1997@reynolds.net',
    ),
    Person(
        name='Emily Ellis',
        gender='F',
        age=18,
        email='emily_ellis 2006@chapman.biz',
    ),
    Person(
        name='Kristen Hess',
        gender='F',
        age=29,
        email='kristen_hess 1995@vasquez-washington.biz',
    ),
    Person(
        name='Paul Perkins',
        gender='M',
        age=21,
        email='paul_perkins 2003@carter.com',
    ),
    Person(
        name='Eric King',
        gender='M',
        age=28,
        email='eric_king 1996@thompson.com',
    ),
    Person(
        name='Kimberly Hunt',
        gender='F',
        age=21,
        email='kimberly_hunt 2003@johnston.biz',
    ),
    Person(
        name='Betty Reed',
        gender='F',
        age=17,
        email='betty_reed 2007@benjamin.com',
    ),
    Person(
        name='Keith Jordan',
        gender='M',
        age=26,
        email='keith_jordan 1998@thompson.com',
    ),
    Person(
        name='Scott Hines',
        gender='M',
        age=29,
        email='scott_hines 1995@riley.com',
    ),
    Person(
        name='Michelle Holder',
        gender='F',
        age=25,
        email='michelle_holder 1999@avila-greer.com',
    ),
    Person(
        name='Vanessa Johnson',
        gender='F',
        age=22,
        email='vanessa_johnson 2002@gonzalez-randolph.com',
    ),
    Person(
        name='Jill Contreras',
        gender='F',
        age=29,
        email='jill_contreras 1995@green.net',
    ),
    Person(
        name='Crystal Suarez',
        gender='F',
        age=22,
        email='crystal_suarez 2002@nunez-jones.com',
    ),
    Person(
        name='Wendy Zamora',
        gender='F',
        age=16,
        email='wendy_zamora 2008@mack.com',
    ),
    Person(
        name='Tammy Rodriguez',
        gender='F',
        age=29,
        email='tammy_rodriguez 1995@patton-dean.com',
    ),
    Person(
        name='Deborah Cowan',
        gender='F',
        age=18,
        email='deborah_cowan 2006@rogers.biz',
    ),
    Person(
        name='Erika Morrison',
        gender='F',
        age=18,
        email='erika_morrison 2006@rodriguez.com',
    ),
    Person(
        name='Cody Tucker',
        gender='M',
        age=25,
        email='cody_tucker 1999@salazar.com',
    ),
    Person(
        name='Megan Shepherd',
        gender='F',
        age=18,
        email='megan_shepherd 2006@white-williams.com',
    ),
    Person(
        name='Jeffrey Ho',
        gender='M',
        age=17,
        email='jeffrey_ho 2007@barker.info',
    ),
    Person(
        name='Carlos Taylor',
        gender='M',
        age=29,
        email='carlos_taylor 1995@nicholson-levine.net',
    ),
    Person(
        name='Steven Mata',
        gender='M',
        age=16,
        email='steven_mata 2008@smith.com',
    ),
    Person(
        name='Bryan Lewis',
        gender='M',
        age=26,
        email='bryan_lewis 1998@stanley.com',
    ),
    Person(
        name='Monica Chandler',
        gender='F',
        age=21,
        email='monica_chandler 2003@brady.biz',
    ),
    Person(
        name='Jason Nguyen',
        gender='M',
        age=19,
        email='jason_nguyen 2005@thompson.com',
    ),
    Person(
        name='Tony Vazquez',
        gender='M',
        age=20,
        email='tony_vazquez 2004@watts-weber.com',
    ),
    Person(
        name='Juan Brewer',
        gender='M',
        age=16,
        email='juan_brewer 2008@martinez-black.org',
    ),
    Person(
        name='Spencer Reynolds',
        gender='M',
        age=24,
        email='spencer_reynolds 2000@stephenson.info',
    ),
    Person(name='Ann Mann', gender='F', age=29, email='ann_mann 1995@cruz.com'),
    Person(
        name='David Palmer',
        gender='M',
        age=19,
        email='david_palmer 2005@campbell.com',
    ),
    Person(
        name='Andrew Ramirez',
        gender='M',
        age=30,
        email='andrew_ramirez 1994@santiago.com',
    ),
    Person(
        name='Joseph Bruce',
        gender='M',
        age=30,
        email='joseph_bruce 1994@thompson-espinoza.com',
    ),
    Person(
        name='Jocelyn Chavez',
        gender='F',
        age=18,
        email='jocelyn_chavez 2006@good.com',
    ),
    Person(
        name='Jade Guerra',
        gender='F',
        age=31,
        email='jade_guerra 1993@brady-mccarthy.info',
    ),
    Person(
        name='Benjamin Mcknight',
        gender='M',
        age=22,
        email='benjamin_mcknight 2002@thompson-mcclain.com',
    ),
    Person(
        name='Elizabeth Ibarra',
        gender='F',
        age=19,
        email='elizabeth_ibarra 2005@williams.net',
    ),
    Person(
        name='Bruce Whitney',
        gender='M',
        age=31,
        email='bruce_whitney 1993@perez.com',
    ),
    Person(
        name='Matthew Parker',
        gender='M',
        age=25,
        email='matthew_parker 1999@jackson.net',
    ),
    Person(
        name='Rachel Harmon',
        gender='F',
        age=29,
        email='rachel_harmon 1995@wood.org',
    ),
    Person(
        name='Travis Wilson',
        gender='M',
        age=17,
        email='travis_wilson 2007@gomez.info',
    ),
]
